version: '3.8'

services:
  client:
    image: lkrbalci/car-sale_client
    ports:
      - "4000:4000"
    depends_on:
      - api
    networks:
      - app-network

  api:
    image: lkrbalci/car-sale_server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    volumes:
      - "/home/lkrbalci/projects/car-sale/uploads:/usr/src/app/uploads"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
