version: '3.8'

services:
  client:
    image: lkrbalci/car-sale_client
    ports:
      - "4000:4000"
    depends_on:
      - server
    networks:
      - app-network

  server:
    image: lkrbalci/car-sale_server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    volumes:
      - "/home/lkrbalci/projects/car-sale/uploads:/usr/src/app/uploads"
      - "/etc/letsencrypt/live/ilker.tinkerbytes.com:/etc/letsencrypt/live/ilker.tinkerbytes.com"
    networks:
      - app-network
    depends_on:
      - certbot

  certbot:
    build:
      context: ./certbot
      dockerfile: Dockerfile
    volumes:
        - "/etc/letsencrypt:/etc/letsencrypt"

networks:
  app-network:
    driver: bridge